// <auto-generated />
using System;
using EGM.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EGM.Infrastructure.Migrations
{
    [DbContext(typeof(EGMDbContext))]
    [Migration("20250412120000_AddCoordinatesToVIPZiyaret")]
    partial class AddCoordinatesToVIPZiyaret
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("EGM.Domain.Entities.VIPZiyaret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GozlemNoktalari")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuvenlikSeviyesi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Hassasiyet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Il")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Mekan")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("TakipNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unvan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZiyaretDurumu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZiyaretEdenAdSoyad")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VIPZiyaretler");
                });

#pragma warning restore 612, 618
        }
    }
}
