// <auto-generated />
using System;
using EGM.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EGM.Infrastructure.Migrations
{
    [DbContext(typeof(EGMDbContext))]
    partial class EGMDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EGM.Domain.Entities.Aday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .HasColumnType("text");

                    b.Property<string>("PartiAdi")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Adaylar");
                });

            modelBuilder.Entity("EGM.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLoglar");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Ekip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<int>("VIPZiyaretId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VIPZiyaretId");

                    b.ToTable("Ekipler");
                });

            modelBuilder.Entity("EGM.Domain.Entities.GuvenlikPlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<int>("VIPZiyaretId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VIPZiyaretId");

                    b.ToTable("GuvenlikPlanlari");
                });

            modelBuilder.Entity("EGM.Domain.Entities.KategoriOrganizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("KategoriOrganizatorler");
                });

            modelBuilder.Entity("EGM.Domain.Entities.KatilimciGrup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GrupAdi")
                        .HasColumnType("text");

                    b.Property<int?>("GrupKatilimciSayisi")
                        .HasColumnType("integer");

                    b.Property<int>("OperasyonelFaaliyetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OperasyonelFaaliyetId");

                    b.ToTable("KatilimciGruplar");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Konu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Konular");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Olay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("BaslangicSaati")
                        .HasColumnType("interval");

                    b.Property<string>("Baslik")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("BitisSaati")
                        .HasColumnType("interval");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GercekBaslangicTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GercekBitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Hassasiyet")
                        .HasColumnType("integer");

                    b.Property<string>("Il")
                        .HasColumnType("text");

                    b.Property<string>("Ilce")
                        .HasColumnType("text");

                    b.Property<int?>("KatilimciSayisi")
                        .HasColumnType("integer");

                    b.Property<string>("KaynakKurum")
                        .HasColumnType("text");

                    b.Property<int>("KonuId")
                        .HasColumnType("integer");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Mekan")
                        .HasColumnType("text");

                    b.Property<string>("OlayTuru")
                        .HasColumnType("text");

                    b.Property<int>("OrganizatorId")
                        .HasColumnType("integer");

                    b.Property<double>("RiskPuani")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KonuId");

                    b.HasIndex("OrganizatorId");

                    b.ToTable("Olaylar");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Olu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KatilimciDurumu")
                        .HasColumnType("text");

                    b.Property<int>("OperasyonelFaaliyetId")
                        .HasColumnType("integer");

                    b.Property<string>("Soyad")
                        .HasColumnType("text");

                    b.Property<string>("TcKimlikNo")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("OperasyonelFaaliyetId");

                    b.ToTable("Oluler");
                });

            modelBuilder.Entity("EGM.Domain.Entities.OperasyonelFaaliyet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("OlayId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OlayId");

                    b.ToTable("OperasyonelFaaliyetler");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Organizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<string>("FaaliyetAlani")
                        .HasColumnType("text");

                    b.Property<string>("Iletisim")
                        .HasColumnType("text");

                    b.Property<DateTime>("KurulusTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Organizatorler");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Parti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Partiler");
                });

            modelBuilder.Entity("EGM.Domain.Entities.SecimKaynak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("KaynakAdi")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SecimKaynaklar");
                });

            modelBuilder.Entity("EGM.Domain.Entities.SecimSonucu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdayId")
                        .HasColumnType("integer");

                    b.Property<int>("BolgeId")
                        .HasColumnType("integer");

                    b.Property<string>("BolgeTipi")
                        .HasColumnType("text");

                    b.Property<int>("KaynakId")
                        .HasColumnType("integer");

                    b.Property<bool>("KaynakOnayDurumu")
                        .HasColumnType("boolean");

                    b.Property<double>("OyOrani")
                        .HasColumnType("double precision");

                    b.Property<int>("OySayisi")
                        .HasColumnType("integer");

                    b.Property<int>("PartiId")
                        .HasColumnType("integer");

                    b.Property<string>("SecimTuru")
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdayId");

                    b.HasIndex("KaynakId");

                    b.HasIndex("PartiId");

                    b.ToTable("SecimSonuclari");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Sehit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Gorev")
                        .HasColumnType("text");

                    b.Property<int>("OperasyonelFaaliyetId")
                        .HasColumnType("integer");

                    b.Property<string>("Soyad")
                        .HasColumnType("text");

                    b.Property<string>("TcKimlikNo")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("OperasyonelFaaliyetId");

                    b.ToTable("Sehitler");
                });

            modelBuilder.Entity("EGM.Domain.Entities.SosyalMedyaOlay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Hassasiyet")
                        .HasColumnType("integer");

                    b.Property<string>("IcerikOzeti")
                        .HasColumnType("text");

                    b.Property<string>("IlgiliKisiKurum")
                        .HasColumnType("text");

                    b.Property<int>("OlayId")
                        .HasColumnType("integer");

                    b.Property<string>("PaylasimLinki")
                        .HasColumnType("text");

                    b.Property<DateTime>("PaylasimTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Platform")
                        .HasColumnType("text");

                    b.Property<double>("SosyalSignalSkoru")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("OlayId");

                    b.ToTable("SosyalMedyaOlaylar");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Supheli", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .HasColumnType("text");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Gozaltinda")
                        .HasColumnType("boolean");

                    b.Property<int>("OperasyonelFaaliyetId")
                        .HasColumnType("integer");

                    b.Property<string>("Soyad")
                        .HasColumnType("text");

                    b.Property<string>("TcKimlikNo")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("OperasyonelFaaliyetId");

                    b.ToTable("Supheliler");
                });

            modelBuilder.Entity("EGM.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GSM")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Sicil")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Sicil")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EGM.Domain.Entities.VIPZiyaret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GozlemNoktalari")
                        .HasColumnType("text");

                    b.Property<string>("GuvenlikSeviyesi")
                        .HasColumnType("text");

                    b.Property<int>("Hassasiyet")
                        .HasColumnType("integer");

                    b.Property<string>("Il")
                        .HasColumnType("text");

                    b.Property<string>("Mekan")
                        .HasColumnType("text");

                    b.Property<string>("Unvan")
                        .HasColumnType("text");

                    b.Property<string>("ZiyaretEdenAdSoyad")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VIPZiyaretler");
                });

            modelBuilder.Entity("EGM.Domain.Entities.YuruyusRota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("NoktaAdi")
                        .HasColumnType("text");

                    b.Property<int>("OlayId")
                        .HasColumnType("integer");

                    b.Property<int>("SiraNo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OlayId");

                    b.ToTable("YuruyusRotasi");
                });

            modelBuilder.Entity("KategoriOrganizatorOrganizator", b =>
                {
                    b.Property<int>("KategorilerId")
                        .HasColumnType("integer");

                    b.Property<int>("OrganizatorlerId")
                        .HasColumnType("integer");

                    b.HasKey("KategorilerId", "OrganizatorlerId");

                    b.HasIndex("OrganizatorlerId");

                    b.ToTable("KategoriOrganizatorOrganizator");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Ekip", b =>
                {
                    b.HasOne("EGM.Domain.Entities.VIPZiyaret", "VIPZiyaret")
                        .WithMany("EkipAtamasi")
                        .HasForeignKey("VIPZiyaretId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VIPZiyaret");
                });

            modelBuilder.Entity("EGM.Domain.Entities.GuvenlikPlani", b =>
                {
                    b.HasOne("EGM.Domain.Entities.VIPZiyaret", "VIPZiyaret")
                        .WithMany("GuvenlikPlanlari")
                        .HasForeignKey("VIPZiyaretId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VIPZiyaret");
                });

            modelBuilder.Entity("EGM.Domain.Entities.KatilimciGrup", b =>
                {
                    b.HasOne("EGM.Domain.Entities.OperasyonelFaaliyet", "OperasyonelFaaliyet")
                        .WithMany("KatilimciGruplar")
                        .HasForeignKey("OperasyonelFaaliyetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperasyonelFaaliyet");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Olay", b =>
                {
                    b.HasOne("EGM.Domain.Entities.Konu", "Konu")
                        .WithMany("Olaylar")
                        .HasForeignKey("KonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGM.Domain.Entities.Organizator", "Organizator")
                        .WithMany("Olaylar")
                        .HasForeignKey("OrganizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Konu");

                    b.Navigation("Organizator");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Olu", b =>
                {
                    b.HasOne("EGM.Domain.Entities.OperasyonelFaaliyet", "OperasyonelFaaliyet")
                        .WithMany("Oluler")
                        .HasForeignKey("OperasyonelFaaliyetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperasyonelFaaliyet");
                });

            modelBuilder.Entity("EGM.Domain.Entities.OperasyonelFaaliyet", b =>
                {
                    b.HasOne("EGM.Domain.Entities.Olay", "Olay")
                        .WithMany("OperasyonelFaaliyetler")
                        .HasForeignKey("OlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Olay");
                });

            modelBuilder.Entity("EGM.Domain.Entities.SecimSonucu", b =>
                {
                    b.HasOne("EGM.Domain.Entities.Aday", "Aday")
                        .WithMany()
                        .HasForeignKey("AdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGM.Domain.Entities.SecimKaynak", "Kaynak")
                        .WithMany()
                        .HasForeignKey("KaynakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGM.Domain.Entities.Parti", "Parti")
                        .WithMany()
                        .HasForeignKey("PartiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aday");

                    b.Navigation("Kaynak");

                    b.Navigation("Parti");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Sehit", b =>
                {
                    b.HasOne("EGM.Domain.Entities.OperasyonelFaaliyet", "OperasyonelFaaliyet")
                        .WithMany("Sehitler")
                        .HasForeignKey("OperasyonelFaaliyetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperasyonelFaaliyet");
                });

            modelBuilder.Entity("EGM.Domain.Entities.SosyalMedyaOlay", b =>
                {
                    b.HasOne("EGM.Domain.Entities.Olay", "Olay")
                        .WithMany("SosyalMedyaOlaylar")
                        .HasForeignKey("OlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Olay");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Supheli", b =>
                {
                    b.HasOne("EGM.Domain.Entities.OperasyonelFaaliyet", "OperasyonelFaaliyet")
                        .WithMany("Supheliler")
                        .HasForeignKey("OperasyonelFaaliyetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperasyonelFaaliyet");
                });

            modelBuilder.Entity("EGM.Domain.Entities.YuruyusRota", b =>
                {
                    b.HasOne("EGM.Domain.Entities.Olay", "Olay")
                        .WithMany("YuruyusRotasi")
                        .HasForeignKey("OlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Olay");
                });

            modelBuilder.Entity("KategoriOrganizatorOrganizator", b =>
                {
                    b.HasOne("EGM.Domain.Entities.KategoriOrganizator", null)
                        .WithMany()
                        .HasForeignKey("KategorilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGM.Domain.Entities.Organizator", null)
                        .WithMany()
                        .HasForeignKey("OrganizatorlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EGM.Domain.Entities.Konu", b =>
                {
                    b.Navigation("Olaylar");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Olay", b =>
                {
                    b.Navigation("OperasyonelFaaliyetler");

                    b.Navigation("SosyalMedyaOlaylar");

                    b.Navigation("YuruyusRotasi");
                });

            modelBuilder.Entity("EGM.Domain.Entities.OperasyonelFaaliyet", b =>
                {
                    b.Navigation("KatilimciGruplar");

                    b.Navigation("Oluler");

                    b.Navigation("Sehitler");

                    b.Navigation("Supheliler");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Organizator", b =>
                {
                    b.Navigation("Olaylar");
                });

            modelBuilder.Entity("EGM.Domain.Entities.VIPZiyaret", b =>
                {
                    b.Navigation("EkipAtamasi");

                    b.Navigation("GuvenlikPlanlari");
                });
#pragma warning restore 612, 618
        }
    }
}
