// <auto-generated />
using System;
using EGM.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EGM.Infrastructure.Migrations
{
    [DbContext(typeof(EGMDbContext))]
    partial class EGMDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("EGM.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLoglar");
                });

            modelBuilder.Entity("EGM.Domain.Entities.EventDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GozaltiSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hassasiyet")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KatilimciSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OlayId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OluSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SehitSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupheliSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OlayId")
                        .IsUnique();

                    b.ToTable("EventDetails");
                });

            modelBuilder.Entity("EGM.Domain.Entities.GerceklesmeSekli", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OlayTuruId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OlayTuruId");

                    b.ToTable("GerceklesmeSekilleri");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("EGM.Domain.Entities.KategoriOrganizator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KategoriOrganizatorler");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Konu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tur")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UstKonuId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UstKonuId");

                    b.ToTable("Konular");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Il")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ilce")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Mahalle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mekan")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OlayId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OlayId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RiskScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bildirimler");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Olay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<bool>("BaslangicBildirimiGonderildi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("KonuId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OlayNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizatorId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SekilId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TurId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaslangicTarihi");

                    b.HasIndex("CityId");

                    b.HasIndex("Durum");

                    b.HasIndex("KonuId");

                    b.HasIndex("OlayNo")
                        .IsUnique();

                    b.HasIndex("OrganizatorId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("SekilId");

                    b.HasIndex("TurId");

                    b.ToTable("Olaylar");
                });

            modelBuilder.Entity("EGM.Domain.Entities.OlayTuru", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OlayTurleri");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Organizator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ad")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Eposta")
                        .HasColumnType("TEXT");

                    b.Property<string>("FaaliyetAlani")
                        .HasColumnType("TEXT");

                    b.Property<string>("Iletisim")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KurulusTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KutukNumarasi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logo")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiyasiYonelim")
                        .HasColumnType("TEXT");

                    b.Property<string>("SosyalMedyaHesaplari")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tur")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UstKurulusId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UstKurulusId");

                    b.ToTable("Organizatorler");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GorselPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OlayId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OlayId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("EGM.Domain.Entities.SandikOlay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GozaltiSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Il")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ilce")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KanitDosyasi")
                        .HasColumnType("TEXT");

                    b.Property<int>("KatilimciSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Konu")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mahalle")
                        .HasColumnType("TEXT");

                    b.Property<string>("MusahitAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Okul")
                        .HasColumnType("TEXT");

                    b.Property<string>("OlayKategorisi")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("OlaySaati")
                        .HasColumnType("TEXT");

                    b.Property<int>("OluSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SandikNo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SehitSayisi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TakipNo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SandikOlaylar");
                });

            modelBuilder.Entity("EGM.Domain.Entities.SosyalMedyaOlay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EkranGoruntusu")
                        .HasColumnType("TEXT");

                    b.Property<int>("Hassasiyet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IcerikOzeti")
                        .HasColumnType("TEXT");

                    b.Property<string>("Il")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ilce")
                        .HasColumnType("TEXT");

                    b.Property<string>("IlgiliKisiKurum")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Konu")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OlayId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaylasimLinki")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PaylasimTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .HasColumnType("TEXT");

                    b.Property<string>("TakipNo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OlayId");

                    b.ToTable("SosyalMedyaOlaylar");
                });

            modelBuilder.Entity("EGM.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GSM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sicil")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.HasIndex("Sicil")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EGM.Domain.Entities.VIPZiyaret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GozlemNoktalari")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuvenlikSeviyesi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Hassasiyet")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Il")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Mekan")
                        .HasColumnType("TEXT");

                    b.Property<string>("TakipNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unvan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZiyaretDurumu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZiyaretEdenAdSoyad")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("VIPZiyaretler");
                });

            modelBuilder.Entity("EGM.Domain.Entities.YuruyusRota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("NoktaAdi")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OlayId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SiraNo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OlayId");

                    b.ToTable("YuruyusRotasi");
                });

            modelBuilder.Entity("GroupOlay", b =>
                {
                    b.Property<Guid>("EventsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParticipantGroupsId")
                        .HasColumnType("TEXT");

                    b.HasKey("EventsId", "ParticipantGroupsId");

                    b.HasIndex("ParticipantGroupsId");

                    b.ToTable("GroupOlay");
                });

            modelBuilder.Entity("KategoriOrganizatorOrganizator", b =>
                {
                    b.Property<Guid>("KategorilerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrganizatorlerId")
                        .HasColumnType("TEXT");

                    b.HasKey("KategorilerId", "OrganizatorlerId");

                    b.HasIndex("OrganizatorlerId");

                    b.ToTable("KategoriOrganizatorOrganizator");
                });

            modelBuilder.Entity("EGM.Domain.Entities.EventDetail", b =>
                {
                    b.HasOne("EGM.Domain.Entities.Olay", "Olay")
                        .WithOne("EventDetail")
                        .HasForeignKey("EGM.Domain.Entities.EventDetail", "OlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Olay");
                });

            modelBuilder.Entity("EGM.Domain.Entities.GerceklesmeSekli", b =>
                {
                    b.HasOne("EGM.Domain.Entities.OlayTuru", "OlayTuru")
                        .WithMany("GerceklesmeSekilleri")
                        .HasForeignKey("OlayTuruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OlayTuru");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Konu", b =>
                {
                    b.HasOne("EGM.Domain.Entities.Konu", "UstKonu")
                        .WithMany("AltKonular")
                        .HasForeignKey("UstKonuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("UstKonu");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Location", b =>
                {
                    b.HasOne("EGM.Domain.Entities.Olay", "Olay")
                        .WithMany("Locations")
                        .HasForeignKey("OlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Olay");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Olay", b =>
                {
                    b.HasOne("EGM.Domain.Entities.Konu", "Konu")
                        .WithMany("Olaylar")
                        .HasForeignKey("KonuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGM.Domain.Entities.Organizator", "Organizator")
                        .WithMany("Olaylar")
                        .HasForeignKey("OrganizatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGM.Domain.Entities.User", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGM.Domain.Entities.GerceklesmeSekli", "Sekil")
                        .WithMany()
                        .HasForeignKey("SekilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGM.Domain.Entities.OlayTuru", "Tur")
                        .WithMany()
                        .HasForeignKey("TurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Konu");

                    b.Navigation("Organizator");

                    b.Navigation("Personel");

                    b.Navigation("Sekil");

                    b.Navigation("Tur");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Organizator", b =>
                {
                    b.HasOne("EGM.Domain.Entities.Organizator", "UstKurulus")
                        .WithMany("AltKuruluslar")
                        .HasForeignKey("UstKurulusId");

                    b.Navigation("UstKurulus");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Resource", b =>
                {
                    b.HasOne("EGM.Domain.Entities.Olay", "Olay")
                        .WithMany("Resources")
                        .HasForeignKey("OlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Olay");
                });

            modelBuilder.Entity("EGM.Domain.Entities.SosyalMedyaOlay", b =>
                {
                    b.HasOne("EGM.Domain.Entities.Olay", "Olay")
                        .WithMany()
                        .HasForeignKey("OlayId");

                    b.Navigation("Olay");
                });

            modelBuilder.Entity("EGM.Domain.Entities.YuruyusRota", b =>
                {
                    b.HasOne("EGM.Domain.Entities.Olay", "Olay")
                        .WithMany()
                        .HasForeignKey("OlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Olay");
                });

            modelBuilder.Entity("GroupOlay", b =>
                {
                    b.HasOne("EGM.Domain.Entities.Olay", null)
                        .WithMany()
                        .HasForeignKey("EventsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGM.Domain.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("ParticipantGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KategoriOrganizatorOrganizator", b =>
                {
                    b.HasOne("EGM.Domain.Entities.KategoriOrganizator", null)
                        .WithMany()
                        .HasForeignKey("KategorilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EGM.Domain.Entities.Organizator", null)
                        .WithMany()
                        .HasForeignKey("OrganizatorlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EGM.Domain.Entities.Konu", b =>
                {
                    b.Navigation("AltKonular");

                    b.Navigation("Olaylar");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Olay", b =>
                {
                    b.Navigation("EventDetail");

                    b.Navigation("Locations");

                    b.Navigation("Resources");
                });

            modelBuilder.Entity("EGM.Domain.Entities.OlayTuru", b =>
                {
                    b.Navigation("GerceklesmeSekilleri");
                });

            modelBuilder.Entity("EGM.Domain.Entities.Organizator", b =>
                {
                    b.Navigation("AltKuruluslar");

                    b.Navigation("Olaylar");
                });
#pragma warning restore 612, 618
        }
    }
}
